package main

var fileTypes = map[string]string{
	".abap":     "abap",
	".ada":      "ada",
	".ahk":      "autohotkey",
	".as":       "actionscript",
	".asciidoc": "AsciiDoc",
	".asm":      "assembly_x86",
	".bat":      "batchfile",
	".bmp":      "Windows bitmap",
	".cpp":      "cpp",
	".csv":      "Comma-Separated Values",
	".dbf":      "DataBase File",
	".dcm":      "Digital Imaging and Communications in Medicine",
	".dif":      "Data Interchange Format",
	".doc":      "Microsoft Document",
	".docx":     "Open XML Microsoft document",
	".dta":      "STATA Data Version 12/13",
	".eps":      "Ecapsulated PostScript",
	".gif":      "Graphics Interchange Format",
	".html":     "HyperText Markup Language",
	".iff":      "Interchange File Format",
	".jpg":      "Joint Photographic Experts Group",
	".ods":      "Open Office Spreadsheet",
	".odt":      "Open Office Text Document",
	".ots":      "Open Office Spreadsheet Template",
	".ott":      "Open Office Text Template",
	".pbm":      "Netpbm format",
	".pct":      "Macintosh picture metafile",
	".pcx":      "Personal Computer Exchange",
	".pdb":      "AportisDoc (Palm)",
	".pdf":      "Portable Document Format",
	".png":      "Portable Network Graphics",
	".ppt":      "Microsoft PowerPoint",
	".pptx":     "Open XML Microsoft PowerPoint",
	".psb":      "Photoshop file",
	".psd":      "Photoshop document",
	".psw":      "Pocket Word",
	".pxr":      "Pixar Image Computer",
	".py":       "python",
	".R":        "R programming language",
	".raw":      "Photoshop Raw File",
	".RData":    "Stored R Object",
	".rtf":      "Rich Text Format",
	".sav":      "SPSS Data",
	".slk":      "SYmbolic LinK",
	".spv":      "SPSS Output File",
	".stc":      "Open Office XML Spreadsheet Template",
	".stw":      "Open Office XML Text Template",
	".svg":      "Scalable Vector Graphics",
	".sxw":      "Open Office XML Text Document",
	".tga":      "Truevision TGA",
	".tif":      "Tagged Image File Format",
	".txt":      "UTF-8 Text File",
	".uos":      "Uniform Office Format 1/2 Spreadsheet",
	".uot":      "Uniform Office Format 1/2 Text",
	".xls":      "Excel Binary",
	".xlsx":     "Open XML Microsoft spreadsheet",
	".xml":      "Microsoft Word 2003 XML",
}
